dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'
      - '@openzeppelinUpgrades=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.0'
autofetch_sources: True
networks:
    development:
        cmd_settings:
            unlock:
                - 0xB39C856b19b619D67c3bBC64cf9A6FcAe96227a1
                - 0xe4A8c1E93F5E674C9901F15C69F7DF2187f6aD27