dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'
      - '@openzeppelinUpgrades=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.0'
autofetch_sources: True
dotenv: .env
networks:
    development:
        cmd_settings:
            unlock: