# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  unit_tests:
  
    defaults:
      run:
        working-directory: smart-contract
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: 3.9.9

    - name: Run Unit tests in brownie
      run: |
        pip install -r requirements.txt
        brownie test 
            
